package wasmcloud:plugin@0.1.0;

world keyvalue-filesystem {

    export wasmcloud:wash/plugin@0.0.2;
    export wasi:keyvalue/store@0.2.0-draft;
    export wasi:keyvalue/atomics@0.2.0-draft;
    export wasi:keyvalue/batch@0.2.0-draft;
}
