name: Release - winget

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: windows-latest
    steps:
     - name: Compile wash
     - run: cargo build --release